@startuml
title Diagrama de Sequencia referente ao CDU001 - Listar todas as Tarefas
actor Usuário
Boundary Frontend
Boundary SpringBoot
Control taskController
Entity Task
Participant taskService
Participant taskRepository
Boundary TypedQuery
Participant Hibernate
Database TodoList
activate SpringBoot
Usuário -> Frontend: Listar todas as Tarefas
activate Usuário
activate Frontend
activate TodoList
Frontend -> SpringBoot: GET api/tasks/
group Roteiro01Application [Spring Boot Java Application]
SpringBoot -> taskController: listAllTasks()
activate taskController
taskController -> taskService: getAllTasks()
activate taskService
taskService -> taskRepository: findAll()
activate taskRepository
taskRepository -> TypedQuery: getResultList(TaskDto)
group JPA Framework[Hibernate]
Activate TypedQuery
TypedQuery -> Hibernate: List(TaskDto)
Activate Hibernate
Hibernate -> TodoList: SELECT * FROM Tasks
TodoList --> Hibernate: Table Tasks
Hibernate --> TypedQuery: Table Tasks
TypedQuery --> taskRepository: List<Tasks>
destroy TypedQuery
end
taskRepository --> taskService: List<Task>
destroy taskRepository
taskService --> taskController: List<Task> tasks
destroy taskService
taskController --> SpringBoot: ResponseEntity<Task> ResponseEntity.ok(tasks)
destroy taskController
end
SpringBoot --> Frontend : ResponseEntity<Task> ResponseEntity.ok(tasks)
Frontend --> Usuário: <list>Task
@enduml
