@startuml
title Diagrama de Sequencia referente ao CDU005 - Editar Tarefa
actor Usuário
Boundary Frontend
Boundary SpringBoot
Control taskController
Entity Task
Participant taskService
Participant taskRepository
Boundary TypedQuery
Participant Hibernate
Database TodoList
activate SpringBoot
Usuário -> Frontend: Editar tarefa
activate Usuário
activate Frontend
activate TodoList
Frontend -> SpringBoot: PUT api/edit/{id}
group Roteiro01Application [Spring Boot Java Application]
SpringBoot -> taskController: updateTask(id, task)
activate taskController
taskController -> taskService: updateTask(id, task)
activate taskService
taskService -> taskRepository: findById(id)
activate taskRepository
taskRepository -> TypedQuery: getSingleResult(Task)
group JPA Framework[Hibernate]
Activate TypedQuery
TypedQuery -> Hibernate: SELECT Task WHERE id = {id}
Activate Hibernate
Hibernate -> TodoList: SELECT * FROM Tasks WHERE id = {id}
TodoList --> Hibernate: Table Task
Hibernate --> TypedQuery: Task
TypedQuery --> taskRepository: Task
destroy TypedQuery
end
taskRepository --> taskService: Task
destroy taskRepository
taskService -> taskRepository: save(task)
activate taskRepository
taskRepository -> TypedQuery: update(Task)
Activate TypedQuery
TypedQuery -> Hibernate: UPDATE Tasks SET [task details] WHERE id = {id}
Hibernate -> TodoList: UPDATE Tasks SET [task details] WHERE id = {id}
TypedQuery --> taskRepository: Task
destroy TypedQuery
end
taskRepository --> taskService: Task
destroy taskRepository
taskService --> taskController: Task task
destroy taskService
taskController --> SpringBoot: ResponseEntity<Task> ResponseEntity.ok(task)
destroy taskController
end
SpringBoot --> Frontend : ResponseEntity<Task> ResponseEntity.ok(task)
Frontend --> Usuário: Task
@enduml
